force-app/main/default/objects/Account/fields/BRR_Scorecard_Used__c.field-meta.xml
<CustomField>
    <fullName>BRR_Scorecard_Used__c</fullName>
    <description>CRM-4364</description>
    <label>BRR Scorecard Used</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Income Producing</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>General Commercial</fullName>
            </value>
            <value>
                <fullName>Behavioural Review</fullName>
            </value>
            <value>
                <fullName>Commercial and Industrial</fullName>
                <isActive>false</isActive>
                <label>Commercial and Industrial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_to_Electronic_Delivery_of_Docume__c.field-meta.xml
<CustomField>
    <fullName>Consent_to_Electronic_Delivery_of_Docume__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent to EDD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_to_General_Email_Communication__c.field-meta.xml
<CustomField>
    <fullName>Consent_to_General_Email_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Consent to general email communication is not required if the member has provided their consent to electronic delivery of documents</inlineHelpText>
    <label>Consent to General Email Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DMC_Invited_By__c.field-meta.xml
<CustomField>
    <fullName>DMC_Invited_By__c</fullName>
    <description>CRM4300 Field to identify the user that sent a DMC invitation to the member to complete the DMC in self serve channel.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DMC Invited By</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Group_Risk_Rating__c</fullName>
    <description>CRM-4364</description>
    <inlineHelpText>Optional</inlineHelpText>
    <label>Group Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LGD_Rating__c.field-meta.xml
<CustomField>
    <fullName>LGD_Rating__c</fullName>
    <description>CRM-3186</description>
    <label>LGD Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>BR1</fullName>
                <isActive>false</isActive>
                <label>BR1</label>
            </value>
            <value>
                <fullName>BR2</fullName>
                <isActive>false</isActive>
                <label>BR2</label>
            </value>
            <value>
                <fullName>BR3</fullName>
                <isActive>false</isActive>
                <label>BR3</label>
            </value>
            <value>
                <fullName>Default</fullName>
                <isActive>false</isActive>
                <label>Default</label>
            </value>
            <value>
                <fullName>K</fullName>
                <isActive>false</isActive>
                <label>K</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Other_Financial_Institution__c.field-meta.xml
<CustomField>
    <fullName>Other_Financial_Institution__c</fullName>
    <description>Motus Project Jira# MBM-110</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Other Financial Institution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PD_Rating__c.field-meta.xml
<CustomField>
    <fullName>PD_Rating__c</fullName>
    <description>CRM-3186</description>
    <label>PD Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>34</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>39</fullName>
            </value>
            <value>
                <fullName>BR1</fullName>
                <isActive>false</isActive>
                <label>BR1</label>
            </value>
            <value>
                <fullName>BR2</fullName>
                <isActive>false</isActive>
                <label>BR2</label>
            </value>
            <value>
                <fullName>BR3</fullName>
                <isActive>false</isActive>
                <label>BR3</label>
            </value>
            <value>
                <fullName>Default</fullName>
                <isActive>false</isActive>
                <label>Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountMergeSyncTest.cls
@isTest

public class AccountMergeSyncTest {
    @isTest static void testAccountMerge() {
        String recTypePerAccId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();

        String moneyChatOwnerId = UserInfo.getUserId(); 

        List <Account> aList = new List <Account> ();
        Account accRecMasterPersonAcc = new Account(FirstName = 'Test Person', LastName= 'Account Master AAC',  
                            RecordTypeId = recTypePerAccId, DMC_Invited_By__c = moneyChatOwnerId, PD_Rating__c = '', LGD_Rating__c = '', 
                            Group_Risk_Rating__c = '', BRR_Scorecard_Used__c = '', Consent_to_Electronic_Delivery_of_Docume__c = false, 
                            Consent_to_General_Email_Communication__c = true);

        aList.add(accRecMasterPersonAcc);

        Account accRecMergedPersonAcc = new Account(FirstName = 'Test Person', LastName= 'Account Merged AAC',  
                            RecordTypeId = recTypePerAccId, DMC_Invited_By__c = moneyChatOwnerId, PD_Rating__c = '', LGD_Rating__c = '', 
                            Group_Risk_Rating__c = '', BRR_Scorecard_Used__c = '', Consent_to_Electronic_Delivery_of_Docume__c = false, 
                            Consent_to_General_Email_Communication__c = true, Other_Financial_Institution__c = 'Motus');
        aList.add(accRecMergedPersonAcc);
        
        insert aList;

        Account aaMaster =  new Account (Id = aList.get(0).Id);
        aList.get(0).PD_Rating__c = '1';
        aList.get(0).LGD_Rating__c = 'A';
        aList.get(0).Group_Risk_Rating__c = '1';
        aList.get(0).BRR_Scorecard_Used__c = 'Income Producing';
        aList.get(0).Consent_to_Electronic_Delivery_of_Docume__c = true;
        aList.get(0).Consent_to_General_Email_Communication__c = true;
  
        update aList;

        Database.merge(aaMaster, aList.get(1).Id);

        AccountMergeSync.getSync (aaMaster.Id);
    }
}