force-app/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>CRM-5813, CRM-6247 - Practice Management - Account Classification</description>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAA</fullName>
            </value>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Interaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Status__c</fullName>
    <formula>IF ( ISBLANK( Next_Account_Team_Interaction__c ) , &quot;&quot;, 
IF (VALUE( SUBSTITUTE( Next_Account_Team_Interaction__c , &quot; Days&quot;, &quot;&quot;) ) &gt; 0, &quot;Completed&quot;, &quot;Overdue&quot;)
)</formula>
    <label>Interaction Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Next_Account_Team_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Next_Account_Team_Interaction__c</fullName>
    <description>Last updated: CRM-6247</description>
    <formula>IF(ISPICKVAL(Classification__c, &quot;&quot;) 
,&quot;&quot;
,TEXT(
   CASE(TEXT(Classification__c), &quot;AAA&quot;, 90, &quot;AA&quot;, 90, &quot;A&quot;, 180, &quot;AS&quot;, 360, &quot;AF&quot;, 360, &quot;B&quot;, 360, &quot;C&quot;, 720, 720)
     - IF (ISBLANK(Last_Account_Team_Interaction__c), ROUND(NOW() -  DATETIMEVALUE(&quot;2024-11-20 00:00:00&quot;), 0), ROUND(NOW() -  Last_Account_Team_Interaction__c, 0)))

+ &quot; Days&quot;)</formula>
    <label>Next Account Team Interaction</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Next_Account_Team_Review__c.field-meta.xml
<CustomField>
    <fullName>Next_Account_Team_Review__c</fullName>
    <description>Last updated: CRM-6247</description>
    <formula>IF(ISPICKVAL(Classification__c, &quot;&quot;) 
,&quot;&quot;
,TEXT(
   CASE(TEXT(Classification__c), &quot;AAA&quot;, 180, &quot;AA&quot;, 180, &quot;A&quot;, 180, &quot;AS&quot;, 360, &quot;AF&quot;, 360, &quot;B&quot;, 360, &quot;C&quot;, 720, 720)
     - IF (ISBLANK(Last_Account_Team_Review__c), ROUND(NOW() -  DATETIMEVALUE(&quot;2024-11-20 00:00:00&quot;), 0), ROUND(NOW() -  Last_Account_Team_Review__c, 0)))

+ &quot; Days&quot;)</formula>
    <label>Next Account Team Review</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Open_Opportunity_Amount__c.field-meta.xml
<CustomField>
    <fullName>Open_Opportunity_Amount__c</fullName>
    <label>Open Opportunity Amount</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>Closed Won, Closed Lost</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Review_Status__c</fullName>
    <formula>IF ( ISBLANK( Next_Account_Team_Review__c) , &quot;&quot;, 
IF (VALUE( SUBSTITUTE( Next_Account_Team_Review__c , &quot; Days&quot;, &quot;&quot;) ) &gt; 0, &quot;Completed&quot;, &quot;Overdue&quot;)
)</formula>
    <label>Review Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PracticeManagementController.cls
public with sharing class PracticeManagementController {
    @AuraEnabled(cacheable=true)
    public static List<AccountWrapper> getAccounts(String userId, String classification, String interactionStatus, String reviewStatus, String houseHoldFlag, String runningUserId) {
    
        String accountQuery = ' Select Id, Name, LastName, PersonContactId, Classification__c, Interaction_Status__c, Open_Opportunity_Amount__c, Next_Account_Team_Interaction__c, Review_Status__c, Next_Account_Team_Review__c, Birthday_in_Next_7_Days__pc From Account Where Id in (Select AccountId From AccountTeamMember WHERE UserId = :userId ) ';
        List <AccountWrapper> acctWrapperList = new List <AccountWrapper> ();
        List <Account> accountList = new List <Account> ();
        AccountWrapper acctWrapper = new AccountWrapper ();

        //String accountQuery = ' Select Id, Name, PersonContactId, Classification__c, Interaction_Status__c, Open_Opportunity_Amount__c, Next_Account_Team_Interaction__c, Review_Status__c, Next_Account_Team_Review__c, LastActivityDate From Account Where Id != null '; //Where Id IN (\'0014c000005MbR7AAK\', \'0014c000005SpzOAAS\')';

        if (!String.isBlank(classification) && classification != 'All')
        {
            if (classification == 'Unclassified') {
                accountQuery = accountQuery + ' And Classification__c = \'\' ';
            }
            else {
                accountQuery = accountQuery + ' And Classification__c = \'' + classification + '\' ';
            }
        }

        if (!String.isBlank(interactionStatus)  && interactionStatus != 'All')
        {
            accountQuery = accountQuery + ' And Interaction_Status__c = \'' + interactionStatus + '\' ';
        }

        if (!String.isBlank(reviewStatus)  && reviewStatus != 'All')
        {
            accountQuery = accountQuery + ' And Review_Status__c = \'' + reviewStatus + '\' ';
        }

        if (!String.isBlank(houseHoldFlag))
        {
            accountQuery = accountQuery;
        }

        accountList = Database.query(accountQuery);

        for (Account aa: accountList)
        {
                
            acctWrapper = new AccountWrapper ();
            acctWrapper.id = aa.Id;
            acctWrapper.name = aa.Name;
            acctWrapper.lastName = String.isBlank(aa.Lastname) ? aa.Name : aa.Lastname ;
            acctWrapper.accountUrl = '/' + aa.Id;
            acctWrapper.personContactId = aa.PersonContactId;
            acctWrapper.classification = aa.Classification__c;
            acctWrapper.interactionStatus = aa.Interaction_Status__c;
            acctWrapper.openOpportunityAmount = '$' + String.valueOf(aa.Open_Opportunity_Amount__c.setScale(2).format());
            acctWrapper.opportunityListUrl = '/lightning/r/Account/' + aa.Id + '/related/Opportunities/view';
            acctWrapper.nextInteractionDue = aa.Next_Account_Team_Interaction__c;
            acctWrapper.nextReviewDue = aa.Next_Account_Team_Review__c;
            acctWrapper.reviewStatus = aa.Review_Status__c;
            acctWrapper.birthdayImage = String.isBlank(aa.Birthday_in_Next_7_Days__pc) ? '':'action:share_thanks';
            acctWrapper.canSelect = true;
            acctWrapperList.Add(acctWrapper);
        }

        /*
        if (userId != runningUserId)
        {
            String accountRunningUserQuery = ' Select Id, Name, PersonContactId, Classification__c, Interaction_Status__c, Open_Opportunity_Amount__c, Next_Account_Team_Interaction__c, Review_Status__c, Next_Account_Team_Review__c From Account Where Id In (Select AccountId From AccountTeamMember WHERE UserId = :runningUserId ) And Id In :accountList '; 

            Map<Id, Account> acctMap = new Map<Id, Account>((List<Account>) Database.query(accountRunningUserQuery));

            for (Account aa: accountList)
            {
                
                acctWrapper = new AccountWrapper ();
                acctWrapper.id = aa.Id;
                acctWrapper.name = aa.Name;
                acctWrapper.accountUrl = '/' + aa.Id;
                acctWrapper.personContactId = aa.PersonContactId;
                acctWrapper.classification = aa.Classification__c;
                acctWrapper.interactionStatus = aa.Interaction_Status__c;
                acctWrapper.openOpportunityAmount = '$' + String.valueOf(aa.Open_Opportunity_Amount__c.setScale(2).format());
                acctWrapper.opportunityListUrl = '/lightning/r/Account/' + aa.Id + '/related/Opportunities/view';
                acctWrapper.nextInteractionDue = aa.Next_Account_Team_Interaction__c;
                acctWrapper.reviewStatus = aa.Review_Status__c;
                acctWrapper.nextReviewDue = aa.Next_Account_Team_Review__c;

                if (acctMap.containsKey(aa.Id))
                {
                    acctWrapper.canSelect = true;
                }
                else
                {
                    acctWrapper.canSelect = false;
                } 

                acctWrapperList.Add(acctWrapper);
            }
        }
        else {
            for (Account aa: accountList)
            {
                
                acctWrapper = new AccountWrapper ();
                acctWrapper.id = aa.Id;
                acctWrapper.name = aa.Name;
                acctWrapper.accountUrl = '/' + aa.Id;
                acctWrapper.personContactId = aa.PersonContactId;
                acctWrapper.classification = aa.Classification__c;
                acctWrapper.interactionStatus = aa.Interaction_Status__c;
                acctWrapper.openOpportunityAmount = '$' + String.valueOf(aa.Open_Opportunity_Amount__c.setScale(2).format());
                acctWrapper.opportunityListUrl = '/lightning/r/Account/' + aa.Id + '/related/Opportunities/view';
                acctWrapper.nextInteractionDue = aa.Next_Account_Team_Interaction__c;
                acctWrapper.reviewStatus = aa.Review_Status__c;
                acctWrapper.nextReviewDue = aa.Next_Account_Team_Review__c;
                acctWrapper.canSelect = true;
                acctWrapperList.Add(acctWrapper);
            }
        }
        */

        return acctWrapperList;
        

    }

    @AuraEnabled
    public static void updateAccounts (List <Account> recordsToUpdate){ 
        update recordsToUpdate; 
    }

    public class AccountWrapper{
        @AuraEnabled public Id id;
        @AuraEnabled public String name;
        @AuraEnabled public String lastName;
        @AuraEnabled public Id personContactId;
        @AuraEnabled public String classification;
        @AuraEnabled public String interactionStatus;
        @AuraEnabled public String openOpportunityAmount; 
        @AuraEnabled public Boolean canSelect;
        @AuraEnabled public String opportunityListUrl;
        @AuraEnabled public String accountUrl;
        @AuraEnabled public String nextInteractionDue;
        @AuraEnabled public String nextReviewDue;
        @AuraEnabled public String reviewStatus;
        @AuraEnabled public String birthdayImage;
    }

}