force-app/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>CRM-5813, CRM-6247 - Practice Management - Account Classification</description>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAA</fullName>
            </value>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Account_Team_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Last_Account_Team_Interaction__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Account Team Interaction</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Account_Team_Review__c.field-meta.xml
<CustomField>
    <fullName>Last_Account_Team_Review__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Account Team Review</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PracticeManagementControllerTest.cls
@isTest
public class PracticeManagementControllerTest {

    
    @isTest
    public static void testPracticeManagementControllerMethod() {
        String recTypePerAccId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();

        List <Account> aaList = new List <Account>();
        aaList.add (new Account(FirstName = 'Test Person', LastName= 'Account AAC', Classification__c = 'AA', Last_Account_Team_Review__c = Date.Today(), Last_Account_Team_Interaction__c = Date.Today(), RecordTypeId = recTypePerAccId));
        aaList.add (new Account(FirstName = 'Test Person', LastName= 'Account AAC', RecordTypeId = recTypePerAccId));
        insert aaList;
        
        List <AccountTeamMember> ATMList = new List <AccountTeamMember>();
        ATMList.add(new AccountTeamMember (UserId = UserInfo.getUserId(), AccountId = aaList.get(0).Id, TeamMemberRole = 'Financial Planner' ));
        ATMList.add(new AccountTeamMember (UserId = UserInfo.getUserId(), AccountId = aaList.get(1).Id, TeamMemberRole = 'Financial Planner' ));
        insert ATMList;

        PracticeManagementController.getAccounts(UserInfo.getUserId(), 'AA', 'Completed', 'Completed', 'True', UserInfo.getUserId());
        PracticeManagementController.getAccounts(UserInfo.getUserId(), 'Unclassified', '', '', 'True', UserInfo.getUserId());
        PracticeManagementController.updateAccounts (aaList);
    }


}